# Generated by Django 4.1.2 on 2023-10-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of publish'),
        ),
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.FloatField(default=0, verbose_name='Average rating'),
        ),
    ]
